#!/bin/sh

######################################
## /usr/local/bin/hdmi_unplug
######################################
X_USER=alexgum
export DISPLAY=:0
export XAUTHORITY=/home/$X_USER/.Xauthority
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
HDMI_STATUS=$(cat /sys/devices/pci0000:00/0000:00:08.1/0000:05:00.0/drm/card0/card0-HDMI-A-1/status)
LID_STATE=$(cat /proc/acpi/button/lid/LID/state | cut -d':' -f2 | tr -d ' ')

connect()
{   
    case $1 in
        "open")
            xrandr --output eDP --primary --auto --output HDMI-A-0 --off
           #  xrandr --output eDP --primary --auto --output HDMI-A-0 --auto --right-of eDP
	   #  if [ ! -z "$(pgrep -fa Xsession | grep qtile)" ]; then
           #      qtile-cmd -o cmd -f restart 2> /dev/null
	   #  fi
	   #  if [ ! -z "$(pgrep -fa Xsession | grep xmonad)" ]; then
           #      echo "*  " > /tmp/displaymode
           #      echo "eDP-HDMI" >> /tmp/displaymode
	   #      [ ! -z "$(pgrep -f xmobar)" ] && pkill -f xmobar
           #      xmonad --restart
	   #  fi
           # nitrogen --restore
            # /home/alexgum/.scripts/bar-launch
            ;;
        "closed")
            xrandr --output eDP --off --output HDMI-A-0 --primary --auto
	    if [ ! -z "$(pgrep -fa Xsession | grep qtile)" ]
	    then
                qtile-cmd -o cmd -f restart 2> /dev/null
	    fi
	    if [ ! -z "$(pgrep -fa Xsession | grep xmonad)" ]
	    then
	        echo " " > /tmp/displaymode
	        echo "HDMI" >> /tmp/displaymode
		# [ ! -z "$(pgrep -f xmobar)" ] && pkill -f xmobar
                xmonad --restart
	    fi
            nitrogen --restore
            # /home/alexgum/.scripts/bar-launch
            ;;
    esac
}

disconnect(){
    xrandr --output eDP --primary --auto --output HDMI-A-0 --off
    if [ ! -z "$(pgrep -fa Xsession | grep qtile)" ]
    then
        qtile-cmd -o cmd -f restart 2> /dev/null
    fi
    if [ ! -z "$(pgrep -fa Xsession | grep xmonad)" ]
    then
        echo " " > /tmp/displaymode
        echo "default" >> /tmp/displaymode
	# [ ! -z "$(pgrep -f xmobar)" ] && pkill -f xmobar
        xmonad --restart
    fi
    nitrogen --restore
    # /home/alexgum/.scripts/bar-launch
}

if [ "${HDMI_STATUS}" = "disconnected" ]; then
    disconnect
elif [ "${HDMI_STATUS}" = "connected" ]; then
    connect "${LID_STATE}"
fi

exit
