#!/bin/sh

DISPLAYS="1:  (Master)
2:  (Master) +  (HDMI)
3:  (HDMI)
4:  (HDMI, Master) +  
5: 來 (Mirror)
6: Manual configuration"

SELECTED=$(printf '%b' "${DISPLAYS}" | rofi -dmenu -fn 'Hack Nerd Font-16' -p ' ' -l 6 -location 0 -yoffset -150 -i -width 400)

HDMI_CONNECTED=$(cat /sys/devices/pci0000:00/0000:00:08.1/0000:05:00.0/drm/card0/card0-HDMI-A-1/status)
DP1_CONNECTED=$(cat /sys/devices/pci0000:00/0000:00:08.1/0000:05:00.0/drm/card0/card0-DP-1/status)
DP2_CONNECTED=$(cat /sys/devices/pci0000:00/0000:00:08.1/0000:05:00.0/drm/card0/card0-DP-2/status)
LID_STATE=$(cat /proc/acpi/button/lid/LID/state | cut -d':' -f2 | tr -d ' ')
DISPLAY_NAME="none"

if [ "${HDMI_CONNECTED}" = "connected" ]
then
    DISPLAY_NAME="HDMI-A-0"
elif [ "${DP1_CONNECTED}" = "connected" ]
then
    DISPLAY_NAME="DisplayPort-0"
elif [ "${DP2_CONNECTED}" = "connected" ]
then
    DISPLAY_NAME="DisplayPort-1"
fi

twm_update(){
    case "$XDG_SESSION_DESKTOP" in
        "qtile") qtile-cmd -o cmd -f restart 2> /dev/null & ;;
        "xmonad") xmonad --restart & ;;
    esac
    xset s off
    xset s noblank
    xset dpms 600 1200 2400
    nitrogen --restore &
    setxkbmap us,ru,de -option -option 'grp:rshift_toggle,caps:ctrl_modifier'
}

default_screen(){
    xrandr --output eDP --primary --auto --output HDMI-A-0 --off --output DisplayPort-0 --off --output DisplayPort-1 --off
    printf " \n" > /tmp/displaymode
    printf "default\n" >> /tmp/displaymode
    printf "" > /tmp/display_num
}

display_only(){
    local DISPLAY_WRITTEN=$(cat /tmp/displayname)
    local CURRENT_MODE=$(tail -n1 /tmp/displaymode)
    if [ "${DISPLAY_WRITTEN}" != "${DISPLAY_NAME}" -o "${CURRENT_MODE}" != "HDMI" ]; then
        case "${DISPLAY_NAME}" in
            "HDMI-A-0")
                xrandr --output eDP --off --output HDMI-A-0 --primary --auto --output DisplayPort-0 --off --output DisplayPort-1 --off
                printf "${DISPLAY_NAME}" > /tmp/displayname
                ;;
            "DisplayPort-0")
                xrandr --output eDP --off --output HDMI-A-0 --off --output DisplayPort-0 --primary --auto --output DisplayPort-1 --off
                printf "${DISPLAY_NAME}" > /tmp/displayname
                ;;
            "DisplayPort-1")
                xrandr --output eDP --off --output HDMI-A-0 --off --output DisplayPort-0 --off --output DisplayPort-1 --primary --auto
                printf "${DISPLAY_NAME}" > /tmp/displayname
                ;;
        esac
        printf " \n" > /tmp/displaymode
        printf "HDMI\n" >> /tmp/displaymode
        printf "" > /tmp/display_num
    fi
}

case ${SELECTED%:*} in
    1)
        case "${LID_STATE}" in
            "open")
                default_screen
                ;;
            "closed")
                display_only
                ;;
        esac
        ;;
    2)
        case "${LID_STATE}" in
            "open")
                DISPLAY_WRITTEN=$(cat /tmp/displayname)
                CURRENT_MODE=$(tail -n1 /tmp/displaymode)
                if [ "${DISPLAY_WRITTEN}" != "${DISPLAY_NAME}" -o "${CURRENT_MODE}" != "eDP-HDMI" ]; then
                    case "${DISPLAY_NAME}" in
                        "HDMI-A-0")
                            xrandr --output eDP --primary --auto --output HDMI-A-0 --auto --right-of eDP --output DisplayPort-0 --off --output DisplayPort-1 --off
                            printf "${DISPLAY_NAME}" > /tmp/displayname
                            ;;
                        "DisplayPort-0")
                            xrandr --output eDP --primary --auto --output HDMI-A-0 --off --output DisplayPort-0 --auto --right-of eDP --output DisplayPort-1 --off
                            printf "${DISPLAY_NAME}" > /tmp/displayname
                            ;;
                        "DisplayPort-1")
                            xrandr --output eDP --primary --auto --output HDMI-A-0 --off --output DisplayPort-0 --off --output DisplayPort-1 --auto --right-of eDP
                            printf "${DISPLAY_NAME}" > /tmp/displayname
                            ;;
                    esac
                    printf "*  \n" > /tmp/displaymode
                    printf "eDP-HDMI\n" >> /tmp/displaymode
                    printf "\n" > /tmp/display_num
                    printf "\n" >> /tmp/display_num
                fi
                ;;
            "closed")
                display_only
                ;;
        esac
        ;;
    3)
        display_only
        ;;
    4)
        case "${LID_STATE}" in
            "open")
                DISPLAY_WRITTEN=$(cat /tmp/displayname)
                CURRENT_MODE=$(tail -n1 /tmp/displaymode)
                if [ "${DISPLAY_WRITTEN}" != "${DISPLAY_NAME}" -o "${CURRENT_MODE}" != "HDMI-eDP" ]; then
                    case "${DISPLAY_NAME}" in
                        "HDMI-A-0")
                            xrandr --output eDP --auto --right-of HDMI-A-0 --output HDMI-A-0 --primary --auto --output DisplayPort-0 --off --output DisplayPort-1 --off
                            printf "${DISPLAY_NAME}" > /tmp/displayname
                            ;;
                        "DisplayPort-0")
                            xrandr --output eDP --auto --right-of DisplayPort-0 --output HDMI-A-0 --off --output DisplayPort-0 --primary --auto --output DisplayPort-1 --off
                            printf "${DISPLAY_NAME}" > /tmp/displayname
                            ;;
                        "DisplayPort-1")
                            xrandr --output eDP --auto --right-of DisplayPort-1 --output HDMI-A-0 --off --output DisplayPort-0 --off --output DisplayPort-1 --primary --auto
                            printf "${DISPLAY_NAME}" > /tmp/displayname
                            ;;
                    esac
                    printf "*  \n" > /tmp/displaymode
                    printf "HDMI-eDP\n" >> /tmp/displaymode
                    printf "\n" > /tmp/display_num
                    printf "\n" >> /tmp/display_num
                fi
                ;;
            "closed")
                display_only
                ;;
        esac
        ;; 
    5)
        case "${LID_STATE}" in
            "open")
                DISPLAY_WRITTEN=$(cat /tmp/displayname)
                CURRENT_MODE=$(tail -n1 /tmp/displaymode)
                if [ "${DISPLAY_WRITTEN}" != "${DISPLAY_NAME}" -o "${CURRENT_MODE}" != "eDP-HDMI-Mirror" ]; then
                    case "${DISPLAY_NAME}" in
                        "HDMI-A-0")
                            xrandr --output eDP --primary --auto --output HDMI-A-0 --auto --same-as eDP --output DisplayPort-0 --off --output DisplayPort-1 --off
                            printf "${DISPLAY_NAME}" > /tmp/displayname
                            ;;
                        "DisplayPort-0")
                            xrandr --output eDP --primary --auto --output HDMI-A-0 --off --output DisplayPort-0 --auto --same-as eDP --output DisplayPort-1 --off
                            printf "${DISPLAY_NAME}" > /tmp/displayname
                            ;;
                        "DisplayPort-1")
                            xrandr --output eDP --primary --auto --output HDMI-A-0 --off --output DisplayPort-0 --off --output DisplayPort-1 --auto --same-as eDP
                            printf "${DISPLAY_NAME}" > /tmp/displayname
                            ;;
                    esac
                    printf "來\n" > /tmp/displaymode
                    printf "eDP-HDMI-Mirror\n" >> /tmp/displaymode
                    printf "" > /tmp/display_num
                fi
                ;;
            "closed")
                display_only
                ;;
        esac
        ;;
    6)
        arandr
        printf "? \n" > /tmp/displaymode
        printf "other\n" >> /tmp/displaymode
        printf "other" > /tmp/displayname
        printf "\n" > /tmp/display_num
        printf "\n" >> /tmp/display_num
        exit 0
        ;;
    # *)
    #     default_screen
    #     twm_update
    #     ;;
esac

twm_update
