#!/bin/sh

HDMI_CONNECTED=$(cat /sys/devices/pci0000:00/0000:00:08.1/0000:05:00.0/drm/card0/card0-HDMI-A-1/status)
DP1_CONNECTED=$(cat /sys/devices/pci0000:00/0000:00:08.1/0000:05:00.0/drm/card0/card0-DP-1/status)
DP2_CONNECTED=$(cat /sys/devices/pci0000:00/0000:00:08.1/0000:05:00.0/drm/card0/card0-DP-2/status)
LID_STATE=$(cat /proc/acpi/button/lid/LID/state | cut -d':' -f2 | tr -d ' ')
DISPLAY_NAME="none"

if [ "${HDMI_CONNECTED}" = "connected" ]
then
    DISPLAY_NAME="HDMI-A-0"
elif [ "${DP1_CONNECTED}" = "connected" ]
then
    DISPLAY_NAME="DisplayPort-0"
elif [ "${DP2_CONNECTED}" = "connected" ]
then
    DISPLAY_NAME="DisplayPort-1"
fi


disconnect_display(){
    xrandr --output eDP --primary --auto --output HDMI-A-0 --off --output DisplayPort-0 --off --output DisplayPort-1 --off
}

twm_update(){
    case "$XDG_SESSION_DESKTOP" in
        "qtile") qtile-cmd -o cmd -f restart 2> /dev/null & ;;
        "xmonad") xmonad --restart & ;;
    esac
    xset s off
    xset s noblank
    xset dpms 600 1200 2400
    nitrogen --restore &
    setxkbmap us,ru,de -option -option 'grp:rshift_toggle,caps:ctrl_modifier'
}

case "${LID_STATE}" in
    "open")
        case "${DISPLAY_NAME}" in
            "none")
                disconnect_display
                printf " \n" > /tmp/displaymode
                printf "default\n" >> /tmp/displaymode
                printf "" > /tmp/display_num
                ;;
            "HDMI-A-0")
                xrandr --output eDP --primary --auto --output HDMI-A-0 --auto --right-of eDP --output DisplayPort-0 --off --output DisplayPort-1 --off
                printf "*  \n" > /tmp/displaymode
                printf "eDP-HDMI\n" >> /tmp/displaymode
                printf "\n" > /tmp/display_num
                printf "\n" >> /tmp/display_num
                ;;
            "DisplayPort-0")
                xrandr --output eDP --primary --auto --output HDMI-A-0 --off --output DisplayPort-0 --auto --right-of eDP --output DisplayPort-1 --off
                printf "*  \n" > /tmp/displaymode
                printf "eDP-HDMI\n" >> /tmp/displaymode
                printf "\n" > /tmp/display_num
                printf "\n" >> /tmp/display_num
                ;;
            "DisplayPort-1")
                xrandr --output eDP --primary --auto --output HDMI-A-0 --off --output DisplayPort-0 --off --output DisplayPort-1 --auto --right-of eDP
                printf "*  \n" > /tmp/displaymode
                printf "eDP-HDMI\n" >> /tmp/displaymode
                printf "\n" > /tmp/display_num
                printf "\n" >> /tmp/display_num
                ;;
        esac
        ;;
    "closed")
        case "${DISPLAY_NAME}" in
            "none")
                disconnect_display
                printf " \n" > /tmp/displaymode
                printf "default\n" >> /tmp/displaymode
                printf "" > /tmp/display_num
                ;;
            "HDMI-A-0")
                xrandr --output eDP --off --output HDMI-A-0 --primary --auto --output DisplayPort-0 --off --output DisplayPort-1 --off
                printf " \n" > /tmp/displaymode
                printf "HDMI\n" >> /tmp/displaymode
                printf "" > /tmp/display_num
                ;;
            "DisplayPort-0")
                xrandr --output eDP --off --output HDMI-A-0 --off --output DisplayPort-0 --primary --auto --output DisplayPort-1 --off
                printf " \n" > /tmp/displaymode
                printf "HDMI\n" >> /tmp/displaymode
                printf "" > /tmp/display_num
                ;;
            "DisplayPort-1")
                xrandr --output eDP --off --output HDMI-A-0 --off --output DisplayPort-0 --off --output DisplayPort-1 --primary --auto
                printf " \n" > /tmp/displaymode
                printf "HDMI\n" >> /tmp/displaymode
                printf "" > /tmp/display_num
                ;;
        esac
        ;;
    *)
        disconnect_display
        printf " \n" > /tmp/displaymode
        printf "default\n" >> /tmp/displaymode
        printf "" > /tmp/display_num
        ;;
esac

twm_update

printf "${DISPLAY_NAME}" > /tmp/displayname
