#!/bin/sh

HDMI_CONNECTED=$(cat /sys/devices/pci0000:00/0000:00:08.1/0000:05:00.0/drm/card0/card0-HDMI-A-1/status)
LID_STATE=$(cat /proc/acpi/button/lid/LID/state | cut -d':' -f2 | tr -d ' ')

twm_update(){
    case "$XDG_SESSION_DESKTOP" in
        "qtile") qtile-cmd -o cmd -f restart 2> /dev/null & ;;
        "xmonad") xmonad --restart & ;;
    esac
    nitrogen --restore &
    setxkbmap us,ru,de -option -option 'grp:rshift_toggle,caps:ctrl_modifier'
}

default_screen(){
    xrandr --output eDP --primary --auto --output HDMI-A-0 --off
    echo " " > /tmp/displaymode
    echo "default" >> /tmp/displaymode
}

case $1 in
    2)
        if [ "${HDMI_CONNECTED}" = "connected" ]; then
            case "${LID_STATE}" in
                "open")
                    xrandr --output eDP --primary --auto --output HDMI-A-0 --auto --right-of eDP
                    echo "*  " > /tmp/displaymode
                    echo "eDP-HDMI" >> /tmp/displaymode
                    twm_update
                    ;;
                "closed")
                    xrandr --output eDP --off --output HDMI-A-0 --primary --auto
                    echo " " > /tmp/displaymode
                    echo "HDMI" >> /tmp/displaymode
                    twm_update
                    ;;
            esac
        fi
        ;;
    3)
        if [ "${HDMI_CONNECTED}" = "connected" ]; then
            xrandr --output eDP --off --output HDMI-A-0 --primary --auto
            echo " " > /tmp/displaymode
            echo "HDMI" >> /tmp/displaymode
            twm_update
            exit 0
        fi
        ;;
    4)
        if [ "${HDMI_CONNECTED}" = "connected" ]; then
            case "${LID_STATE}" in
                "open")
                    xrandr --output HDMI-A-0 --primary --auto --output eDP --auto --right-of HDMI-A-0
                    echo "*  " > /tmp/displaymode
                    echo "eDP-HDMI" >> /tmp/displaymode
                    twm_update
                    ;;
                "closed")
                    xrandr --output eDP --off --output HDMI-A-0 --primary --auto
                    echo " " > /tmp/displaymode
                    echo "HDMI" >> /tmp/displaymode
                    twm_update
                    ;;
            esac
        fi
        ;; 
    5)
        if [ "${HDMI_CONNECTED}" = "connected" ]; then
            case "${LID_STATE}" in
                "open")
                    xrandr --output eDP --primary --auto --output HDMI-A-0 --auto --same-as eDP
                    echo "來" > /tmp/displaymode
                    echo "eDP-HDMI-Mirror" >> /tmp/displaymode
                    ;;
                "closed")
                    xrandr --output eDP --off --output HDMI-A-0 --primary --auto
                    echo " " > /tmp/displaymode
                    echo "HDMI" >> /tmp/displaymode
                    twm_update
                    ;;
            esac
        fi
        ;;
    6)
        arandr
        echo "? " > /tmp/displaymode
        echo "other" >> /tmp/displaymode
        twm_update
        exit 0
        ;;
    *)
        default_screen
        twm_update
        exit 0
        ;;
esac

