#!/bin/sh

HDMI_CONNECTED=$(cat /sys/devices/pci0000:00/0000:00:08.1/0000:05:00.0/drm/card0/card0-HDMI-A-1/status)
LID_STATE=$(cat /proc/acpi/button/lid/LID/state | cut -d':' -f2 | tr -d ' ')

twm_update(){
    case "$XDG_SESSION_DESKTOP" in
        "qtile") qtile-cmd -o cmd -f restart 2> /dev/null & ;;
        "xmonad") xmonad --restart & ;;
    esac
    nitrogen --restore &
    setxkbmap us,ru,de -option -option 'grp:rshift_toggle,caps:ctrl_modifier'
}

case "${LID_STATE}" in
    "open")
        if [ "${HDMI_CONNECTED}" = "disconnected" ]; then
            xrandr --output eDP --primary --auto --output HDMI-A-0 --off
            echo " " > /tmp/displaymode
            echo "default" >> /tmp/displaymode
            twm_update
            exit 0
        fi 
        if [ "${HDMI_CONNECTED}" = "connected" ]; then
            xrandr --output eDP --primary --auto --output HDMI-A-0 --auto --right-of eDP
            echo "*  " > /tmp/displaymode
            echo "eDP-HDMI" >> /tmp/displaymode
            twm_update
            exit 0
        fi
        ;;
    "closed")
        if [ "${HDMI_CONNECTED}" = "connected" ]; then
            xrandr --output eDP --off --output HDMI-A-0 --primary --auto
            echo " " > /tmp/displaymode
            echo "HDMI" >> /tmp/displaymode
            twm_update
            exit 0
        fi
        if [ "${HDMI_CONNECTED}" = "disconnected" ]; then
            xrandr --output eDP --primary --auto --output HDMI-A-0 --off
            echo " " > /tmp/displaymode
            echo "default" >> /tmp/displaymode
            twm_update
            exit 0
        fi
        ;;
    *)
        xrandr --output eDP --primary --auto --output HDMI-A-0 --off
        echo " " > /tmp/displaymode
        echo "default" >> /tmp/displaymode
        twm_update
        exit 0
        ;;
esac
