#!/bin/sh

PLAYBACK_STATE=$(amixer | grep "Playback" | fgrep "[off]")
DEFAULT_SINK=$(pactl info | grep "^Default Sink" | awk '{print $3}')
DEFAULT_SINK_ID=$(pactl list sinks short | grep "$DEFAULT_SINK" | awk '{print $1}' | tail -n1)
# CURRENT_PLAYBACK_VOLUME=$(amixer get 'Master' | tail -n1 | cut -d'[' -f2 | cut -d'%' -f1)
CURRENT_PLAYBACK_VOLUME=$(pactl get-sink-volume "$DEFAULT_SINK_ID" | grep Volume | awk '{print $5}' | tr -d '%')


[ ! -e /tmp/volumexob ] && mkfifo /tmp/volumexob

if [ -z $(grep "m$" /tmp/displaymode) ]
then
    profile=volume_left
else
    profile=volume_right
fi

(tail -f /tmp/volumexob | xob -m 100 -t 2000 -s "$profile" > /dev/null 2> /dev/null &)

volumeratioshow(){
    # amixer get Master | tail -n1 | cut -d'[' -f2 | cut -d'%' -f1 > /tmp/volumexob
    pactl get-sink-volume "$DEFAULT_SINK_ID" | grep Volume | awk '{print $5}' | tr -d '%' > /tmp/volumexob
}


# volumeratioshow

case $1 in
    -up)
        if [ ! -z "$PLAYBACK_STATE" ]
        then
            pactl set-sink-mute "$DEFAULT_SINK_ID" toggle
            volumeratioshow
        fi
        case $CURRENT_PLAYBACK_VOLUME in
            [0-2])
                pactl set-sink-volume "$DEFAULT_SINK_ID" 5%
                volumeratioshow
                ;;
            *)
                pactl set-sink-volume "$DEFAULT_SINK_ID" +5%
                volumeratioshow
                ;;
        esac
        ;;
    -down)
        if [ ! -z "$PLAYBACK_STATE" ]
        then
            pactl set-sink-mute "$DEFAULT_SINK_ID" toggle
            volumeratioshow
        fi
        case $CURRENT_PLAYBACK_VOLUME in
            [0-4])
                pactl set-sink-mute "$DEFAULT_SINK_ID" 1
                printf "0\n" > /tmp/volumexob
                ;;
            *)
                pactl set-sink-volume "$DEFAULT_SINK_ID" -5%
                volumeratioshow
                ;;
        esac
        ;;
    -mutetoggle)
        if [ ! -z "$PLAYBACK_STATE" ]
        then
            pactl set-sink-mute "$DEFAULT_SINK_ID" toggle
            # amixer set Master toggle
            volumeratioshow
        fi
        if [ -z "$PLAYBACK_STATE" ]
        then
            pactl set-sink-mute "$DEFAULT_SINK_ID" toggle
            # amixer set Master toggle
            printf "0\n" > /tmp/volumexob
        fi
        ;;
esac

sleep 3s
pkill -f "tail -f /tmp/volumexob"
