#!/bin/sh

MAX_BRIGHTNESS=255
MIN_BRIGHTNESS=1
STEP=20

CURRENT_BRIGHTNESS=$(pkexec /usr/bin/xfpm-power-backlight-helper --get-brightness)

[ ! -e /tmp/brightnessxob ] && mkfifo /tmp/brightnessxob

(tail -f /tmp/brightnessxob | xob -m 255 -t 2000 -s backlight > /dev/null 2> /dev/null &)

case $1 in
    -up)
        if [ $CURRENT_BRIGHTNESS -ge $(expr $MAX_BRIGHTNESS - $STEP) ]; then
            pkexec /usr/bin/xfpm-power-backlight-helper --set-brightness $MAX_BRIGHTNESS
            echo 255 > /tmp/brightnessxob
        else
            BRIGHTNESS=$(expr $CURRENT_BRIGHTNESS + $STEP)
            pkexec /usr/bin/xfpm-power-backlight-helper --set-brightness $BRIGHTNESS
            echo $BRIGHTNESS > /tmp/brightnessxob
        fi
        ;;
    -down)
        if [ $CURRENT_BRIGHTNESS -le $(expr $STEP + 1) ]; then
            pkexec /usr/bin/xfpm-power-backlight-helper --set-brightness $MIN_BRIGHTNESS
            echo 1 > /tmp/brightnessxob
        else
            BRIGHTNESS=$(expr $CURRENT_BRIGHTNESS - $STEP) 
            pkexec /usr/bin/xfpm-power-backlight-helper --set-brightness $BRIGHTNESS
            echo $BRIGHTNESS > /tmp/brightnessxob
        fi
        ;;
esac

sleep 3s && pkill -f "tail -f /tmp/brightnessxob"
