#!/bin/sh

MAX_BRIGHTNESS=255
MIN_BRIGHTNESS=1
STEP=20
STEP_MIN=$(( $STEP + 1 ))

CURRENT_BRIGHTNESS=$(pkexec /usr/bin/xfpm-power-backlight-helper --get-brightness)
echo $CURRENT_BRIGHTNESS

[ ! -e /tmp/brightnessxob ] && mkfifo /tmp/brightnessxob

(tail -f /tmp/brightnessxob | xob -m 255 -t 2000 -s backlight > /dev/null 2> /dev/null &)

case "$1" in
    "-up")
        if [ $CURRENT_BRIGHTNESS -ge $(( $MAX_BRIGHTNESS - $STEP )) ]; then
            pkexec /usr/bin/xfpm-power-backlight-helper --set-brightness $MAX_BRIGHTNESS
            printf "255\n" > /tmp/brightnessxobl
        else
            BRIGHTNESS=$(( $CURRENT_BRIGHTNESS + $STEP ))
            pkexec /usr/bin/xfpm-power-backlight-helper --set-brightness $BRIGHTNESS
            printf "$BRIGHTNESS\n" > /tmp/brightnessxob
        fi
        ;;
    "-down")
        if [ $CURRENT_BRIGHTNESS -le $STEP_MIN ]; then
            pkexec /usr/bin/xfpm-power-backlight-helper --set-brightness $MIN_BRIGHTNESS
            printf "255\n" > /tmp/brightnessxob
        else
            BRIGHTNESS=$(( $CURRENT_BRIGHTNESS - $STEP )) 
            pkexec /usr/bin/xfpm-power-backlight-helper --set-brightness $BRIGHTNESS
            printf "$BRIGHTNESS\n" > /tmp/brightnessxob
        fi
        ;;
esac

sleep 3s
pkill -f "tail -f /tmp/brightnessxob"
