#!/bin/sh

max_brightness=255
min_brightness=35
step_size=15

current_brightness=$(pkexec /usr/bin/xfpm-power-backlight-helper --get-brightness)

[ ! -e /tmp/brightnessxob ] && mkfifo /tmp/brightnessxob

if [ -z $(grep "m$" /tmp/displaymode) ]
then
    profile=backlight_left
else
    profile=backlight_right
fi

(tail -f /tmp/brightnessxob | xob -m 255 -t 2000 -s "$profile" > /dev/null 2> /dev/null &)

case "$1" in
    "-up")
        BRIGHTNESS=$(( $current_brightness + $step_size ))
        if [ $BRIGHTNESS -ge $max_brightness ]; then
            pkexec /usr/bin/xfpm-power-backlight-helper --set-brightness $max_brightness
            printf "255\n" > /tmp/brightnessxobl
        else
            pkexec /usr/bin/xfpm-power-backlight-helper --set-brightness $BRIGHTNESS
            printf "$BRIGHTNESS\n" > /tmp/brightnessxob
        fi
        ;;
    "-down")
        BRIGHTNESS=$(( $current_brightness - $step_size )) 
        if [ $BRIGHTNESS -le $min_brightness ]; then
            pkexec /usr/bin/xfpm-power-backlight-helper --set-brightness $min_brightness
            printf "$min_brightness\n" > /tmp/brightnessxob
        else
            pkexec /usr/bin/xfpm-power-backlight-helper --set-brightness $BRIGHTNESS
            printf "$BRIGHTNESS\n" > /tmp/brightnessxob
        fi
        ;;
esac

sleep 3s
pkill -f "tail -f /tmp/brightnessxob"
