#!/bin/sh

# Take password prompt from STDIN, print password to STDOUT
# the sed piece just removes the colon from the provided
# prompt: rofi -p already gives us a colon
rofi -dmenu -password -location 0 -no-fixed-num-lines -p "$(printf '%s' "${1}" | sed 's/://; s/\//\n/g' | tail -n1)"
